### ISSUE TITLE
支持rocketmq Kafka之类的驱动吗

### ISSUE THREAD

**Issue by no-serve-people** [gookit/event#18]
**System (please complete the following information):**

 - OS: `linux` [e.g. linux, macOS]
 - GO Version: `1.13` [e.g. `1.13`]
 - Pkg Version: `1.1.1` [e.g. `1.1.1`]

**Describe the bug**

**To Reproduce**

```go
// go code
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zhangsean** [comment]
我也想问，目前event是单机单实例应用内的事件驱动，如果可以整合第三方消息服务，马上就可以支持分布式多应用多实例事件驱动了，应用范围和空间讲大范围扩展啊。

**Comment by inhere** [comment]
那样做的太复杂了...
