### ISSUE TITLE
Any more examples on how to use some of the capabilities?

### ISSUE THREAD

**Issue by lonnietc** [gookit/event#30]
Hello,

I am developing a new type of database that will also allow for event triggers when things are added, modified, deleted, etc. as well as a number of other functionality as this will be a type of Graph database.

The use of triggers should substantially the capabilities of the database for the user and so far, your "event" repo seems like it is the best one that I have come across for this purpose.

It would be nice to see a number of different examples showing various capabilities of the library.

Do you have more examples that I could see?
Thanks

**Comment by inhere** [comment]
hello, @lonnietc 

I updated the README to add more examples. What other of examples do you need?

**Comment by lonnietc** [comment]
Thanks for updating the README.

I think that those will be good and I can go from there with how I am trying to integrate you library into my project.
