### ISSUE TITLE
Possible to add Event Timer Triggers?

### ISSUE THREAD

**Issue by lonnietc** [gookit/event#31]
Hello,

I am liking your Event library more and more as I think that it really has good potential.

One question is as to how well it scales?

and another question is if it could be extended to allow for setting up of Timed Event Triggers that would fire:

1.  Fire on a particular Time or Date?
2.  Fire periodically as to say every 30 seconds, or minutes, etc.  (maybe event shorter or longer time intervals)?
3.  Other ways that times might be used?

Then functions could be activated based upon timed events.

This would be a very useful addition.
Thanks

**Comment by inhere** [comment]
hi @lonnietc  For timed-triggered events, maybe you should go with a package like this

 https://github.com/robfig/cron

**Comment by lonnietc** [comment]
Hello,

Thanks for your reply on this.

I actually already know of cron, which is used on a number of systems, but I was thinking about it in terms of being an addition to an Event Trigger library since I will be using the other capabilities of the event trigger library as well and having it all integrated into a single library would seem best for my purposes.

**Comment by inhere** [comment]
hi, Thanks for your reply. 

:) You means is add some like `TriggerAfter` `TriggerTimerd` methods?

**Comment by lonnietc** [comment]
Hello,

It was all just a thought for an enhancement to your Event library since what I am developing is a type of Graph database which basically has nodes and edges with relationships.

My thought were to have Trigger Events for:

1. Event Trigger (Before/After) Creating/Deleting/Modifying/Reading/Writing of Nodes, Edges, and Relationships --- This will be covered by your current Event Trigger Methods.

```
- On/Listen(name string, listener Listener, priority ...int) Register event listener
- Subscribe/AddSubscriber(sbr Subscriber) Subscribe to support registration of multiple event listeners
- Trigger/Fire(name string, params M) (error, Event) Trigger event
- MustTrigger/MustFire(name string, params M) Event Trigger event, there will be panic if there is an error
- FireEvent(e Event) (err error) Trigger an event based on a given event instance
- FireBatch(es ...interface{}) (ers []error) Trigger multiple events at once
- AsyncFire(e Event) Async fire event by 'go' keywords
```
 
2. Timed Triggers -- These would be timer-based trigger (like a built in cron library perhaps) which allow the user to have maybe:

Timer.on(date, Event.Fire("e1", nil))
or
Timer.onevery(30, Event.Fire("e1", nil))    -- Where the time could be seconds, minutes, hours, etc..  I was also thinking about sub-seconds events and even fire as fast as possible to one or more events which could be one-to-one, or one-to-many events, etc.

Basically still thinking about it, but this type of idea would also allow the graph database to perform as a specialize Spiking Neural Network as well as be heavily event driven no matter if the event is functional action based or timer based.  This could be extended to include modules for watching physical ports and addresses to fire events based upon changes.

Mostly still playing with some ideas, but I think that your Event Triggers library may have huge potential to cover many different types of events and many use cases that are currently not covered by other Event Trigger libraries.

Of course, I also still have the big question as to how large your library can scale since a Graph Database could have many thousands of Nodes-Edges and thus many thousands (ore more) of events to be watched for different types of triggers.

Just some thoughts that I had on this idea, though and you may have other ideas as well.

I see that your main methods are:

**Comment by inhere** [comment]
`I see that your main methods are:` has more message after this?

**Comment by inhere** [comment]
oh, ok. thanks for you reply.
