### ISSUE TITLE
Channels on Fire func 

### ISSUE THREAD

**Issue by AlexeySpiridonov** [gookit/event#39]
The library is very good. 

But I am interested in working under high load. 

Have you thought about adding channel support to event.Fire()?  That would be able to handle load peaks?

**Comment by AlexeySpiridonov** [comment]
I need handle more than 50 000 evens /sec

**Comment by AlexeySpiridonov** [comment]
Like AsyncFire but through channels?

**Comment by inhere** [comment]
@AlexeySpiridonov hi, add the feature on `v1.1.0`:

- add new options on create manager:

```go

	// ChannelSize for fire events by goroutine
	ChannelSize int
	ConsumerNum int
```

- add new method for push event to channel:

```go
(em *Manager) Async(name string, params M)
(em *Manager) FireC(name string, params M)
(em *Manager) FireAsync(e Event)
```

> NOTE: should call the method Close() after exit program.
