### ISSUE TITLE
functionality Wildcard

### ISSUE THREAD

**Issue by mmavka** [gookit/event#43]
Thanks a lot for the library. Let me ask a question.
Are there any plans to implement the functionality Wildcard event name ex. `"eve.some.*.*"` and  `"eve.some.*.run"`?

**Comment by flyinghail** [comment]
@inhere It might be simpler to use `path.Match` instead of `regexp`.

**Comment by inhere** [comment]
Thanks, I will add it at next version.

**Comment by inhere** [comment]
hi @mmavka the feature added on `v1.1.0`, and released.
you can enable it by set option: `MatchMode = ModePath`

```go
em := event.NewManager("test", event.UsePathMode)
```
