### ISSUE TITLE
这个触发异步事件有具体的写法 贴一下吗

### ISSUE THREAD

**Issue by JueMeiAlg** [gookit/event#55]
我这边下载的版本 好像和 文档里面的不一样 需要 传入一个 Event参数 这个参数怎么构建呢

**Comment by inhere** [comment]
可以使用 Async/FireC/FireAsync 方法触发事件，事件将会写入 chan 异步消费。可以使用 CloseWait() 关闭chan并等待事件全部消费完成。

- Async/FireC(name string, params M) 投递事件到 chan，异步消费处理
- FireAsync(e Event) 投递事件到 chan，异步消费处理

event.NewBasic() 可以创建通用的Event实例； Async/FireC 无需构建 Event，内部构建的。

> 文档 https://github.com/gookit/event/blob/master/README.zh-CN.md#%E5%BC%82%E6%AD%A5%E6%B6%88%E8%B4%B9%E4%BA%8B%E4%BB%B6

**Comment by JueMeiAlg** [comment]
感谢
